"""Request and response models for the SeshOps triage pipeline.

These are non-table SQLModels used exclusively as API contract types.
They replace the former ``schemas/operations.py`` as part of the SQLModel
unification — keeping all data definitions in a single ``models/`` package.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class TriageRequest(BaseModel):
    """Payload submitted by an operator to initiate an incident triage.

    Attributes:
        incident_input: Free-text alert or user description of the incident.
    """

    incident_input: str = Field(
        ...,
        description="The raw alert or user text describing the incident.",
    )


class TriageResponse(BaseModel):
    """Structured result returned after the triage pipeline completes.

    Attributes:
        service_name: The LLM-identified affected service.
        symptoms: The LLM-identified symptoms from the alert.
        diagnostic_summary: The final diagnostic summary from the LangGraph.
    """

    service_name: str = Field(
        ..., description="The LLM-identified affected service."
    )
    symptoms: str = Field(
        ..., description="The LLM-identified symptoms from the alert."
    )
    diagnostic_summary: str = Field(
        ..., description="The final output summary generated by the triage pipeline."
    )
